save_checkpoint_steps: 10150
seed: 1
train_steps: 10150
valid_steps: 406
report_every: 200
train_from: models/curriculum1_m=3/lstms2s_24.pt
encoder_type: brnn
decoder_type: rnn
word_vec_size: 100
rnn_size: 100
layers: 2
dropout: 0.3
batch_size: 20
seed: 1
optim: adadelta
learning_rate: 1.0

world_size: 1
gpu_ranks:
- 0

# Corpus opts:
data:
    corpus_1:
        path_src: ../data/curriculum1_m=3/train_epoch=25.src
        path_tgt: ../data/curriculum1_m=3/train_epoch=25.tgt
    valid:
        path_src: ../data/unimorph/val.src
        path_tgt: ../data/unimorph/val.tgt
save_model: models/curriculum1_m=3/lstms2s_25
save_data: data_preprocessed/unimorph
src_vocab: data_preprocessed/unimorph.vocab.src
tgt_vocab: data_preprocessed/unimorph.vocab.tgt
overwrite: true

