save_checkpoint_steps: 4872
seed: 1
train_steps: 4872
valid_steps: 406
report_every: 200
train_from: models/no_curriculum_seed=1/lstms2s_11.pt
encoder_type: brnn
decoder_type: rnn
word_vec_size: 100
rnn_size: 100
layers: 2
dropout: 0.3
batch_size: 20
optim: adadelta
learning_rate: 1.0

world_size: 1
gpu_ranks:
- 0

# Corpus opts:
data:
    corpus_1:
        path_src: ../data/unimorph/train.src
        path_tgt: ../data/unimorph/train.tgt
    valid:
        path_src: ../data/unimorph/val.src
        path_tgt: ../data/unimorph/val.tgt
save_model: models/no_curriculum_seed=1/lstms2s_12
save_data: data_preprocessed/unimorph
src_vocab: data_preprocessed/unimorph.vocab.src
tgt_vocab: data_preprocessed/unimorph.vocab.tgt
overwrite: true

